# GitHub Sponsors (if available)
github: []

# Patreon / Ko-fi / BuyMeACoffee (not used now)
patreon: ""
ko_fi: ""
buy_me_a_coffee: ""

# Open Collective (jika ada)
open_collective: ""

# Custom sponsorship links
custom:
  - "https://autodigitalcoin.com"
  - "https://t.me/ADCoinhelpline"
  - "https://adc-assetguard-ai.onrender.com"
